'use client';
import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, Bell, Check, ChevronRight, Settings, HelpCircle, UserPlus, Calendar, CreditCard, X } from 'lucide-react';
import { useRevolutStore } from '@/store/useRevolutStore';
import { ReferenceActivity } from './ReferenceActivity';
import { formatCurrencyAmount } from '@/utils/formatters';

export function PresentationPanels() {
  const state=useRevolutStore();
  const [name,setName]=useState('');
  const [amount,setAmount]=useState('100');
  const [asset,setAsset]=useState('AAPL');
  const [sell,setSell]=useState(false);
  const [message,setMessage]=useState('');
  const [contactId,setContactId]=useState('c-briana');
  const [date,setDate]=useState('');
  const [browserStatus,setBrowserStatus]=useState('');
  const [helpQuery,setHelpQuery]=useState('');
  useEffect(()=>{setMessage('');},[state.uiPanel]);
  useEffect(()=>{state.processScheduledPayments();const timer=window.setInterval(()=>useRevolutStore.getState().processScheduledPayments(),30000);return()=>window.clearInterval(timer);},[]);
  if(!state.uiPanel)return null;
  if(state.uiPanel==='activity')return <ReferenceActivity/>;
  const titles={profile:'Profile',notifications:'Notifications',scheduled:'Scheduled payments','new-contact':'Add recipient',help:'Help',invest:'Invest',crypto:'Crypto',rewards:'RevPoints',plan:'Your plan'};
  const panel=state.uiPanel;
  const field='w-full bg-white/10 rounded-xl p-3 text-white outline-none';
  return <motion.section key={panel} role="dialog" aria-modal="true" aria-label={titles[panel]} initial={{x:20,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:.18}} className="presentation-panel no-scrollbar">
    <header><button className="reference-back" aria-label="Close menu" onClick={()=>state.setUiPanel(null)}><ArrowLeft/></button><h1>{titles[panel]}</h1></header>
    {panel==='profile'&&<><div className="presentation-profile"><img src="/profile.png" alt="Profile"/><h2>Mihai</h2><p>{state.selectedPlan}</p></div><div className="presentation-menu">{[{label:'Notifications',Icon:Bell,panel:'notifications' as const},{label:'Your plan',Icon:CreditCard,panel:'plan' as const},{label:'Scheduled payments',Icon:Calendar,panel:'scheduled' as const},{label:'Add recipient',Icon:UserPlus,panel:'new-contact' as const},{label:'Help',Icon:HelpCircle,panel:'help' as const}].map(item=><button key={item.label} onClick={()=>state.setUiPanel(item.panel)}><item.Icon/><span>{item.label}</span><ChevronRight/></button>)}<button onClick={()=>{state.setUiPanel(null);state.setGodModeOpen(true);}}><Settings/><span>Presentation settings</span><ChevronRight/></button></div><div className="presentation-about"><strong>Revolut interface prototype</strong><p>Project presentation. All balances, cards, investments and payments are simulated. This app does not connect to Revolut or Apple Pay.</p></div></>}
    {panel==='notifications'&&<><label className="presentation-toggle">Payment notifications<input type="checkbox" checked={state.notificationsEnabled} onChange={event=>state.setNotificationsEnabled(event.target.checked)}/></label><label className="presentation-toggle">Notification sounds<input type="checkbox" checked={state.soundEnabled} onChange={event=>state.setSoundEnabled(event.target.checked)}/></label><div className="flex gap-3 my-5"><button className={field} onClick={()=>state.markNotificationsRead()}>Mark all read</button><button className={field} onClick={()=>state.notify('Test notification','Your in-app notifications are working.')}>Send test</button></div><button className="text-blue-300 text-sm mb-4" onClick={async()=>{if(!('Notification' in window)){setBrowserStatus('This browser does not support system notifications. In-app notifications are available.');return;}const permission=await Notification.requestPermission();setBrowserStatus(permission==='granted'?'System notifications enabled.':'Permission was not granted.');if(permission==='granted')new Notification('Revolut prototype',{body:'This is a demo notification.',icon:'/icon-192.png'});}}>Enable browser notifications</button>{browserStatus&&<p className="text-white/50 text-sm mb-4">{browserStatus}</p>}{state.notifications.map(item=><button className="presentation-notification" key={item.id} onClick={()=>{state.markNotificationsRead();state.setUiPanel('activity');}}><Bell/><span><strong>{item.title}</strong><small>{item.message}</small></span>{!item.read&&<i/>}</button>)}</>}
    {panel==='new-contact'&&<form className="space-y-4" onSubmit={event=>{event.preventDefault();if(!name.trim())return;state.addContact(name);setName('');setMessage('Recipient added');}}><label className="block">Name<input className={field+' mt-2'} aria-label="Recipient name" value={name} onChange={event=>setName(event.target.value)} required/></label><button className="presentation-primary">Add recipient</button></form>}
    {panel==='scheduled'&&<><div className="space-y-4"><label className="block">Recipient<select className={field+' mt-2'} value={contactId} onChange={event=>setContactId(event.target.value)}>{state.contacts.map(contact=><option className="bg-[#222]" key={contact.id} value={contact.id}>{contact.name}</option>)}</select></label><label className="block">Amount in RON<input className={field+' mt-2'} type="number" min=".01" step=".01" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="block">Date and time<input className={field+' mt-2'} type="datetime-local" value={date} onChange={event=>setDate(event.target.value)}/></label><button className="presentation-primary" onClick={()=>setMessage(state.schedulePayment(contactId,Number(amount),date)||'Payment scheduled')}>Schedule payment</button></div><div className="mt-6 space-y-4">{state.scheduledPayments.map(item=><div key={item.id} className={field}><p>{state.contacts.find(contact=>contact.id===item.contactId)?.name} · {item.amount} RON</p><p className="text-white/50 text-sm">{new Date(item.date).toLocaleString('en-GB')} · {item.status}</p>{item.status==='scheduled'&&<button className="text-blue-300 mt-3" onClick={()=>state.cancelScheduledPayment(item.id)}>Cancel payment</button>}</div>)}</div></>}
    {(panel==='invest'||panel==='crypto')&&<div className="space-y-5"><p className="text-white/50">Practice with fictional holdings and fixed values.</p><label className="block">Asset<select className={field+' mt-2'} value={asset} onChange={event=>setAsset(event.target.value)}>{(panel==='crypto'?['BTC','ETH','SOL','AAPL']:['AAPL','MSFT','NVDA','BTC']).map(value=><option className="bg-[#222]" key={value}>{value}</option>)}</select></label><div className="flex gap-3"><button className={field+(sell?'':' ring-1 ring-blue-400')} onClick={()=>setSell(false)}>Buy</button><button className={field+(sell?' ring-1 ring-blue-400':'')} onClick={()=>setSell(true)}>Sell</button></div><p>Available: {formatCurrencyAmount(sell?state.demoHoldings[asset]||0:state.accounts.RON.balance,'RON')}</p><label className="block">Amount in RON<input type="number" min=".01" step=".01" className={field+' mt-2'} value={amount} onChange={event=>setAmount(event.target.value)}/></label><button className="presentation-primary" onClick={()=>setMessage(state.tradeDemo(asset,Number(amount),sell)||'Demo order completed')}>{sell?'Sell':'Buy'} {asset}</button><h2 className="text-xl">Your holdings</h2>{Object.entries(state.demoHoldings).map(([symbol,value])=><p key={symbol}>{symbol}: {formatCurrencyAmount(value,'RON')}</p>)}</div>}
    {panel==='rewards'&&<><h2 className="text-4xl mb-5">{state.revPoints} points</h2><p className="text-white/50 mb-5">Choose a reward for your presentation.</p>{[{label:'Shopping discount',points:500},{label:'Travel reward',points:1000}].map(reward=><button className="presentation-notification" key={reward.label} onClick={()=>setMessage(state.redeemPoints(reward.points)||`${reward.label} redeemed`)}><span><strong>{reward.label}</strong><small>{reward.points} points</small></span><ChevronRight/></button>)}</>}
    {panel==='plan'&&<div className="space-y-4">{['Standard','Plus','Premium','Metal','Ultra'].map(plan=><button className="presentation-notification" key={plan} onClick={()=>state.selectPlan(plan)}><span>{plan}</span>{state.selectedPlan===plan&&<Check/>}</button>)}<p className="text-white/50 text-sm">Plans are simulated. No subscriptions or charges are created.</p></div>}
    {panel==='help'&&<><input aria-label="Search help" className={field} value={helpQuery} onChange={event=>setHelpQuery(event.target.value)} placeholder="Search help"/>{[{title:'Adding money',body:'Open Home → Add money, enter an amount, choose Apple Pay and confirm the demo payment.'},{title:'Transfers',body:'Open Payments and select a recipient. Amounts move only within this prototype.'},{title:'Notifications',body:'Profile → Notifications contains the notification history and preferences.'},{title:'About this project',body:'This presentation reproduces supplied interface references. It has no connection to banking or payment networks.'}].filter(item=>(item.title+item.body).toLowerCase().includes(helpQuery.toLowerCase())).map(item=><details className="bg-white/5 rounded-2xl p-4 my-4" key={item.title}><summary>{item.title}</summary><p className="text-white/50 mt-3 text-sm">{item.body}</p></details>)}</>}
    {message&&<p role="status" className="my-5 text-blue-300">{message}</p>}
  </motion.section>;
}

export function NotificationToast() {
  const state=useRevolutStore();
  const latest=state.notifications[0];
  const [visible,setVisible]=useState(false);
  useEffect(()=>{if(latest&&!latest.read&&Date.now()-latest.timestamp<1000&&state.notificationsEnabled){setVisible(true);const timer=window.setTimeout(()=>setVisible(false),4500);if('Notification' in window&&Notification.permission==='granted')new Notification('Revolut prototype',{body:latest.message,icon:'/icon-192.png'});return()=>window.clearTimeout(timer);}},[latest?.id,state.notificationsEnabled]);
  return <AnimatePresence>{visible&&latest&&<motion.aside initial={{y:-100,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-100,opacity:0}} className="reference-toast" role="status"><button className="flex-1 text-left" onClick={()=>{setVisible(false);state.setUiPanel('notifications');}}><strong>{latest.title}</strong><span>{latest.message}</span></button><button aria-label="Dismiss notification" onClick={()=>setVisible(false)}><X size={18}/></button></motion.aside>}</AnimatePresence>;
}
